# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Checkout submodules for tutorial content
submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      # Fetch full git history and tags for hatch-vcs to determine version
      - git fetch --unshallow || true
      - git fetch --tags
      # Create empty server data directory (normally created by frontend build)
      # Must run before pip install, not pre_build which runs after
      - mkdir -p src/experimaestro/server/data

# Build documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Python requirements for documentation
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
