site_name: Experimaestro (Python)
site_description: experimaestro Computer science experiments manager and scheduler

nav:
  - Introduction: index.md
  - Tutorial: tutorial.md
  - Experiments:
      - Configuration: experiments/config.md
      - Task: experiments/task.md
      - Plan: experiments/plan.md
  - Launchers: launchers/index.md
  - Connectors: connectors/index.md
  - Serialization: serialization.md
  - Settings: settings.md
  - Running experiments: experiments.md
  - Services: services.md
  - Integration:
      - Jupyter: jupyter.md
      - Documentation: documenting.md
  - CLI: cli.md
  - Changelog: changelog.md
  - FAQ: faq.md

theme:
  name: readthedocs

markdown_extensions:
  - codehilite:
      linenums: false
  - admonition
  - pymdownx.superfences
  # See https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation
  - pymdownx.snippets:
      base_path: .


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            heading_level: 4
            show_root_full_path: False
            docstring_style: sphinx
  - search

repo_url: "https://github.com/experimaestro/experimaestro-python"

extra_css:
  - style.css
