tar xzf poco-${POCO_VERSION}-release.tar.gz
cd poco-poco-${POCO_VERSION}-release
export POCO_STATIC=1
rm -rf cmake-build
mkdir cmake-build
cd cmake-build
cmake -DPOCO_STATIC=OFF -DENABLE_REDIS=OFF -DENABLE_XML=ON -DENABLE_PAGECOMPILER=OFF -DENABLE_PAGECOMPILER_FILE2PAGE=OFF -DENABLE_DATA_ODBC=OFF -DENABLE_PDF=OFF -DENABLE_POCODOC=OFF -DENABLE_MONGODB=OFF -DENABLE_CPPPARSER=OFF -DENABLE_DATA_MYSQL=OFF -DCMAKE_BUILD_TYPE=Release ..
make -j${COMPILE_THREADS}
make install